language: java

jdk:
  - openjdk8

script:
  - "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
  - docker build -t voting-tg-app-backend .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag back $DOCKER_USER/voting-tg-app-backend:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/voting-tg-app-backend:$TRAVIS_BUILD_NUMBER
  - docker tag back $DOCKER_USER/voting-tg-app-backend:latest
  - docker push $DOCKER_USER/voting-tg-app-backend:latest